### ISSUE TITLE
.htaccess not working 

### ISSUE THREAD

**Issue by trungegd** [jetsung/docker-nginx-php#10]
I just created docker image from php 7.3 version.
I used Volume for my container. 
My problem is .htaccess not working on nginx server.

Please help me for fix it.

Thanks in advance!

**Comment by flydo** [comment]
```.htaccess``` rules can only be used in ``apache server.`` 
> https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/

**htaccess to nginx converter tool**: https://winginx.com/en/htaccess

**Comment by trungegd** [comment]
Thanks for your reply @skiy.
One more question:
I created container from php 7.4 version and show php info page it is php 7.4. But when I login in to container (used command: docker exec -ti container_id bash) and run: php -v, then result is php 5.4.16 (cli).
phpinfo page: https://prnt.sc/r1cb7d
command php -v in container : https://prnt.sc/r1cbt6

Can you explain it?

**Comment by flydo** [comment]
This problem has been solved.

**Comment by trungegd** [comment]
Thank @skiy 
Will take a look it when have time.
