### ISSUE TITLE
v3版本有严重BUG

### ISSUE THREAD

**Issue by netyilei** [jetsung/docker-nginx-php#11]
目前PHP7.4版本对很多老代码支持并不好,就比如我现在的项目一些组件就用不了。 所以一直在用PHP7.3

前天开始捣鼓升级成您的V3版本。  发现在访问频繁情况下会连不上REDIS 这个问题测试了很久。
更换过redis版本，修改过REDIS的LINUX服务器的网络参数 都无法解决。 一度认为是您的V3版本有BUG。

后用宝塔，编译安装PHP7 依然出现这个问题。 这才发现，是最新的PHP7.20有这个BUG。
请作者更新一下V3版本  等待继续使用您的PHP7版本

**Comment by afisme** [comment]
你可以按 **README.md** 说明，使用 `main` 版本的代码来构建编译：   
```bash
git clone https://github.com/skiy/docker-nginx-php.git
cd nginx-php
```

- 方式一：直接编译
```bash
docker build --build-arg PHP_VERSION="7.3.33" \
  --build-arg NGINX_VERSION="1.20.0" \
  -t nginx-php:7.3 \
  -f ./Dockerfile .
```

- 方式二：一键编译脚本 **build.sh**：
  文件 `.env`
```bash
# PHP 和 NGINX 版本号
# 7.3.330 => PHP：7.3.33
# Docker tag: 7.3.330 则为 nginx-php:7.3.330 / nginx-php:7.3
IMAGE_VERSION=7.3.330
NGINX_VERSION=1.21.5

# 若为中国镜像需要设置，若使用国外 VPS 编译，可以删除以下两行
GH_MIRROR_URL=https://ghproxy.com/
CN_MIRROR=1

# 是否推送到 (Docker Registry)
D_PUSH=false
# 编译构架
D_PLATFORM="linux/amd64"
```

然后执行 `./build.sh xxx env 0` 来编译
> 参数说明：   
xxx 为你的 Docker Registry (默认: hub.docker.com) 用户名   
env 为是否使用 `.env`   
0 为不使用 `buildx` 构建 

## 注意：
1、若是需要推送，则需要先手动登录到对应的 `Docker Registry`，比如官方的 `https://docker.io`：   
```bash
docker login -u xxx -p https://docker.io
```

2、镜像不内置 `redis` 扩展，需要将 https://github.com/skiy/docker-nginx-php/blob/main/extensions/redis.sh 中的代码复制到文件 `extension.sh` 中，再使用参数 `-v` 挂载过去。挂载方式：https://github.com/skiy/docker-nginx-php/tree/main/docs#custom-extension

---
由于我误将 `skiychan` 转成组织时，并且转让给了别人，目前我只有 PUSH 权限。刚刚 `PUSH` 了一个 V3 版本：https://hub.docker.com/r/skiychan/nginx-php7/tags?page=1&name=v3

你可以按上述方式执行时添加 `redis` 扩展看看。

**Comment by netyilei** [comment]
好的， 谢谢您！ 万分感谢

**Comment by afisme** [comment]
已重新构建了一个包含 `fileinfo,pq,raphf,imagick,redis` 等常用扩展的 **PHP 7.3** 镜像。
该镜像使用 `supervisord` 管理 PHP 和 NGINX  服务，方便自行添加 PHP 扩展和 NGINX 添加新 host 后，重载服务。

Docker Hub 地址为：https://hub.docker.com/r/devcto/nginx-php
```bash
docker pull devcto/nginx-php:7.3
```
