### ISSUE TITLE
自从镜像更换了系统后，并发时redis会出问题

### ISSUE THREAD

**Issue by netyilei** [jetsung/docker-nginx-php#12]
自从镜像更换了操作系统后，在并发时， redis会有连不上的情况。
查了下资料  说是没有可用使用的端口， 修改系统参数 加快端口回收也于事无补。
请作者检测此问题 更帮助解决下。  谢谢

**Comment by flydo** [comment]
> 自从镜像更换了操作系统后，在并发时， redis会有连不上的情况。 查了下资料 说是没有可用使用的端口， 修改系统参数 加快端口回收也于事无补。 请作者检测此问题 更帮助解决下。 谢谢

1、如何复现你的问题呢？
2、redis 也是安装在此镜像中？
3、相关日志及 docker-compose 内容是否有？
