### ISSUE TITLE
"Inappropriate ioctl for device" when running yum install

### ISSUE THREAD

**Issue by stumpdk** [jetsung/docker-nginx-php#3]
I'm running an unaltered version of the nginx-php7 image (latest). I get the following error when I try to install new packages, such as Nano:

> yum install nano

Am I using the wrong credentials to log in?

**Comment by David20111030** [comment]
！！！请教！！！！
报错：
panic: standard_init_linux.go:178: exec user process caused "no such file or directory" [recovered]
panic: standard_init_linux.go:178: exec user process caused "no such file or directory"
