### ISSUE TITLE
Enabling Volume for www  folder

### ISSUE THREAD

**Issue by frogydiak** [jetsung/docker-nginx-php#5]
NiHao!

I enabled volumes for data/www and restarted the docker, and I get a forbidden error 403. What is the proper way of enabling www in my local volume? I am running docker on Mac using Kitematic. 

Thanks!

**Comment by flydo** [comment]
You need to create a new container, and take ```-v /data/www:/data/www```, and then execute it, see the example: https://github.com/skiy-dockerfile/nginx-php7/wiki/Example#%E4%BD%BF%E7%94%A8%E6%8C%87%E5%AE%9A%E7%9A%84%E7%9B%AE%E5%BD%95%E4%BD%9C%E4%B8%BA%E7%BD%91%E7%AB%99%E8%AE%BF%E9%97%AE%E7%9B%AE%E5%BD%95

```
docker run --name nginx1 \
-p 8081:80 \
-v /data/www:/data/www \
-d skiychan/nginx-php7:nightly
```
