### ISSUE TITLE
How to set nginx log stdout ?

### ISSUE THREAD

**Issue by wangsinovatech** [jetsung/docker-nginx-php#9]
hello skiy ~   I try ln -sv /dev/stdout /var/log/nginx_access.log && ln -sv /dev/stderr /var/log/nginx_error.log IN Dockerfile  ，  But Can't work   , please help

**Comment by flydo** [comment]
You need to modify the ```nginx.conf``` file. 
```
access_log  /var/log/nginx/nginx_access.log;

**Comment by wangsinovatech** [comment]
I modify nginx.conf  access_log  /dev/stdout  error_log /dev/stderr
 can't display nginx log in the console （docker logs -f container
<https://www.baidu.com/link?url=gQbUOj5RFQmtrgxSSwXJMMKJDXajegq03wnftYhHlKjPujbGHT4MTj8OGSgQKQ7fcjPXu3w4tgOzSPmyKyfkV4B_i_HNU81sM-A4NJCTOra&wd=&eqid=d396759500030513000000065cf77dc3>
ID）

Skiychan <notifications@github.com> 于2019年6月4日周二 下午3:44写道：

**Comment by wangsinovatech** [comment]
I don't know what's your meaning ...
But I  modify vhost/test.conf  access_log  /dev/stdout  error_log /dev/stderr   
can't display nginx log in the console （docker logs -f containerID）  

Do you mean modify the nginx.conf  access_log /var/log/nginx/nginx_access.log;   and  modify Dockerfile  ln -sv /dev/stdout /var/log/nginx/nginx_access.log . cat display nginx log in  the console （docker logs -f containerID）

**Comment by wangsinovatech** [comment]
I want to output the logs of nginx and php-fpm to the console.

Now the output of the console is the log of supervisord

**Comment by wangsinovatech** [comment]
@skiy Thank you, I have solved the problem.

**Comment by gh0sthx** [comment]
> @skiy Thank you, I have solved the problem.

How did you solve the problem?
